### ISSUE TITLE
[1.5pt] User authentication

### ISSUE THREAD

**Issue by AlphaNtihinduka** [AlphaNtihinduka/car_cruise_rental#2]
- A new user should be able to create an account using sign up form
- The user logs in to the website, only by typing the username
- Implement proper user authentication from the front end to the server.

**Comment by 41hulk** [comment]
Using this resource [Auth with jwt](https://www.bluebash.co/blog/rails-6-7-api-authentication-with-jwt-2/) found in microverse documentation to implement auth on users

**Comment by 41hulk** [comment]
Just fixed issues and logical errors

**Comment by 41hulk** [comment]
Integrated the API to log in on the front end 🚀 .
**Next up:** Integrate the sign up on the front-end

**Comment by 41hulk** [comment]
Done with signup and login rebasing to the main branch to wrap this up
